name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'slides/main.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install tectonic
        run: |
          wget https://github.com/tectonic-typesetting/tectonic/releases/download/v0.7.1/tectonic-v0.7.1-x86_64-unknown-linux-gnu.tar.gz
          tar xzf tectonic-v0.7.1-x86_64-unknown-linux-gnu.tar.gz
          sudo cp tectonic-v0.7.1-x86_64-unknown-linux-gnu/* /usr/local/bin/

      - name: Install Fonts
        run: |
          sudo apt-get update && sudo apt-get install -y fonts-firacode

      - name: Build PDF
        run: tectonic slides/main.tex --print

      - name: Copy PDF to artifacts
        run: cp main.pdf $GITHUB_WORKSPACE

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
