name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install tectonic
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh

      - name: Install Fonts
        run: |
          sudo apt-get update && sudo apt-get install -y fonts-firacode

      - name: Build PDF
        run: tectonic slides/main.tex --print

      - name: Copy PDF to artifacts
        run: cp main.pdf $GITHUB_WORKSPACE

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
