name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Fira Font
        id: install-font
        run: |
          curl -o FiraSans.zip "https://fonts.google.com/download?family=Fira%20Sans"
          unzip FiraSans.zip
          sudo mkdir -p /usr/local/share/fonts/FiraSans
          sudo cp FiraSans-*.ttf /usr/local/share/fonts/FiraSans
          sudo fc-cache -fv
          
      - uses: actions/cache@v3
        id: font-cache
        with:
          path: /usr/local/share/fonts/FiraSans
          key: ${{ runner.os }}-font-cache-${{ hashFiles('FiraSans-*.ttf') }}

      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd slides
          tectonic main.tex
          cd ..

      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: slides/main.pdf
