name: Build and Publish Thesis

on:
  push:
    branches:
      - main
    paths:
      - 'thesis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: '2.17'

      - name: Build
        run: |
          cd thesis
          tectonic main.tex
          cd ..

      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: thesis/main.pdf
